// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ErrorDisplayV1() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Error Display --><div data-show=\"$v1Tab.error !== ''\" class=\"mt-8 bg-red-50 border-l-4 border-red-500 rounded-lg p-6 shadow-sm animate-fade-in relative group error-card\"><div class=\"flex items-start\"><div class=\"flex-shrink-0\"><svg class=\"h-6 w-6 text-red-500\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg></div><div class=\"ml-3 flex-1\"><h3 class=\"text-sm font-semibold text-red-800 mb-1\">Something went wrong</h3><p class=\"text-sm text-red-700 error-text\" data-text=\"$v1Tab.error\"></p></div></div><!-- Copy Error Button --><button type=\"button\" class=\"absolute top-4 right-4 inline-flex items-center justify-center p-2.5 rounded-lg border font-semibold transition-all duration-200 shrink-0\" data-class:bg-sky-50=\"!$v1Tab.copied\" data-class:border-sky-500=\"!$v1Tab.copied\" data-class:text-sky-600=\"!$v1Tab.copied\" data-class:hover:bg-sky-500=\"!$v1Tab.copied\" data-class:hover:text-white=\"!$v1Tab.copied\" data-class:bg-emerald-50=\"$v1Tab.copied\" data-class:border-emerald-300=\"$v1Tab.copied\" data-class:text-emerald-600=\"$v1Tab.copied\" data-on:click=\"navigator.clipboard.writeText($v1Tab.error); $v1Tab.copied = true; setTimeout(() => $v1Tab.copied = false, 1000)\" title=\"Copy error\"><i class=\"fas fa-copy text-md\" data-show=\"!$v1Tab.copied\"></i> <i class=\"fas fa-check text-md\" data-show=\"$v1Tab.copied\"></i></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ErrorDisplayV2() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Error Display --><div data-show=\"$v2Tab.error !== ''\" class=\"mt-8 bg-red-50 border-l-4 border-red-500 rounded-lg p-6 shadow-sm animate-fade-in relative group error-card\"><div class=\"flex items-start\"><div class=\"flex-shrink-0\"><svg class=\"h-6 w-6 text-red-500\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg></div><div class=\"ml-3 flex-1\"><h3 class=\"text-sm font-semibold text-red-800 mb-1\">Something went wrong</h3><p class=\"text-sm text-red-700 error-text\" data-text=\"$v2Tab.error\"></p></div></div><!-- Copy Error Button --><button type=\"button\" class=\"absolute top-4 right-4 inline-flex items-center justify-center p-2.5 rounded-lg border font-semibold transition-all duration-200 shrink-0\" data-class:bg-sky-50=\"!$v2Tab.copied\" data-class:border-sky-500=\"!$v2Tab.copied\" data-class:text-sky-600=\"!$v2Tab.copied\" data-class:hover:bg-sky-500=\"!$v2Tab.copied\" data-class:hover:text-white=\"!$v2Tab.copied\" data-class:bg-emerald-50=\"$v2Tab.copied\" data-class:border-emerald-300=\"$v2Tab.copied\" data-class:text-emerald-600=\"$v2Tab.copied\" data-on:click=\"navigator.clipboard.writeText($v2Tab.error); $v2Tab.copied = true; setTimeout(() => $v2Tab.copied = false, 1000)\" title=\"Copy error\"><i class=\"fas fa-copy text-md\" data-show=\"!$v2Tab.copied\"></i> <i class=\"fas fa-check text-md\" data-show=\"$v2Tab.copied\"></i></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ErrorDisplayV3() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Error Display --><div data-show=\"$v3Tab.error !== ''\" class=\"mt-8 bg-red-50 border-l-4 border-red-500 rounded-lg p-6 shadow-sm animate-fade-in relative group error-card\"><div class=\"flex items-start\"><div class=\"flex-shrink-0\"><svg class=\"h-6 w-6 text-red-500\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg></div><div class=\"ml-3 flex-1\"><h3 class=\"text-sm font-semibold text-red-800 mb-1\">Something went wrong</h3><p class=\"text-sm text-red-700 error-text\" data-text=\"$v3Tab.error\"></p></div></div><!-- Copy Error Button --><button type=\"button\" class=\"absolute top-4 right-4 inline-flex items-center justify-center p-2.5 rounded-lg border font-semibold transition-all duration-200 shrink-0\" data-class:bg-sky-50=\"!$v3Tab.copied\" data-class:border-sky-500=\"!$v3Tab.copied\" data-class:text-sky-600=\"!$v3Tab.copied\" data-class:hover:bg-sky-500=\"!$v3Tab.copied\" data-class:hover:text-white=\"!$v3Tab.copied\" data-class:bg-emerald-50=\"$v3Tab.copied\" data-class:border-emerald-300=\"$v3Tab.copied\" data-class:text-emerald-600=\"$v3Tab.copied\" data-on:click=\"navigator.clipboard.writeText($v3Tab.error); $v3Tab.copied = true; setTimeout(() => $v3Tab.copied = false, 1000)\" title=\"Copy error\"><i class=\"fas fa-copy text-md\" data-show=\"!$v3Tab.copied\"></i> <i class=\"fas fa-check text-md\" data-show=\"$v3Tab.copied\"></i></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ErrorDisplaySafe() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- Error Display --><div data-show=\"$safeTab.error !== ''\" class=\"mt-8 bg-red-50 border-l-4 border-red-500 rounded-lg p-6 shadow-sm animate-fade-in relative group error-card\"><div class=\"flex items-start\"><div class=\"flex-shrink-0\"><svg class=\"h-6 w-6 text-red-500\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg></div><div class=\"ml-3 flex-1\"><h3 class=\"text-sm font-semibold text-red-800 mb-1\">Something went wrong</h3><p class=\"text-sm text-red-700 error-text\" data-text=\"$safeTab.error\"></p></div></div><!-- Copy Error Button --><button type=\"button\" class=\"absolute top-4 right-4 inline-flex items-center justify-center p-2.5 rounded-lg border font-semibold transition-all duration-200 shrink-0\" data-class:bg-sky-50=\"!$safeTab.copied\" data-class:border-sky-500=\"!$safeTab.copied\" data-class:text-sky-600=\"!$safeTab.copied\" data-class:hover:bg-sky-500=\"!$safeTab.copied\" data-class:hover:text-white=\"!$safeTab.copied\" data-class:bg-emerald-50=\"$safeTab.copied\" data-class:border-emerald-300=\"$safeTab.copied\" data-class:text-emerald-600=\"$safeTab.copied\" data-on:click=\"navigator.clipboard.writeText($safeTab.error); $safeTab.copied = true; setTimeout(() => $safeTab.copied = false, 1000)\" title=\"Copy error\"><i class=\"fas fa-copy text-md\" data-show=\"!$safeTab.copied\"></i> <i class=\"fas fa-check text-md\" data-show=\"$safeTab.copied\"></i></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func ErrorDisplaySmart() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<!-- Error Display --><div data-show=\"$smartTab.error !== ''\" class=\"mt-8 bg-red-50 border-l-4 border-red-500 rounded-lg p-6 shadow-sm animate-fade-in relative group error-card\"><div class=\"flex items-start\"><div class=\"flex-shrink-0\"><svg class=\"h-6 w-6 text-red-500\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg></div><div class=\"ml-3 flex-1\"><h3 class=\"text-sm font-semibold text-red-800 mb-1\">Something went wrong</h3><p class=\"text-sm text-red-700 error-text\" data-text=\"$smartTab.error\"></p></div></div><!-- Copy Error Button --><button type=\"button\" class=\"absolute top-4 right-4 inline-flex items-center justify-center p-2.5 rounded-lg border font-semibold transition-all duration-200 shrink-0\" data-class:bg-sky-50=\"!$smartTab.copied\" data-class:border-sky-500=\"!$smartTab.copied\" data-class:text-sky-600=\"!$smartTab.copied\" data-class:hover:bg-sky-500=\"!$smartTab.copied\" data-class:hover:text-white=\"!$smartTab.copied\" data-class:bg-emerald-50=\"$smartTab.copied\" data-class:border-emerald-300=\"$smartTab.copied\" data-class:text-emerald-600=\"$smartTab.copied\" data-on:click=\"navigator.clipboard.writeText($smartTab.error); $smartTab.copied = true; setTimeout(() => $smartTab.copied = false, 1000)\" title=\"Copy error\"><i class=\"fas fa-copy text-md\" data-show=\"!$smartTab.copied\"></i> <i class=\"fas fa-check text-md\" data-show=\"$smartTab.copied\"></i></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
